ascii_chars = {
    'A': [
        "   A   ",
        "  A A  ",
        " A   A ",
        "AAAAAAA",
        "A     A"
    ],
    'B': [
        "BBBB ",
        "B   B",
        "BBBB ",
        "B   B",
        "BBBB ",
    ],
    'C': [
        " CCC ",
        "C   C",
        "C    ",
        "C   C",
        " CCC ",
    ],
     'D': [
        "DDDD  ",
        "D   D ",
        "D   D ",
        "D   D ",
        "DDDD  ",
    ],
    'E': [
        "EEEE ",
        "E    ",
        "EEE  ",
        "E    ",
        "EEEE ",
    ],
    'F': [
        "FFFFF",
        "F    ",
        "FFF  ",
        "F    ",
        "F    ",
    ],
    'G': [
        " GGG ",
        "G    ",
        "G  GG",
        "G   G",
        " GGG ",
    ],
    'H': [
        "H   H",
        "H   H",
        "HHHHH",
        "H   H",
        "H   H",
    ],
    'I': [
        " III  ",
        "  I   ",
        "  I   ",
        "  I   ",
        " III  ",
    ],
    'J': [
        " JJ  ",
        "  J  ",
        "  J  ",
        "J J  ",
        " JJ  ",
    ],
    'K': [
        "K   K",
        "K  K ",
        "KKK  ",
        "K  K ",
        "K   K",
    ],
    'L': [
        "L    ",
        "L    ",
        "L    ",
        "L    ",
        "LLLLL",
    ],
    'M': [
        "M   M",
        "MM MM",
        "M M M",
        "M   M",
        "M   M",
    ],
    'N': [
        "N   N",
        "NN  N",
        "N N N",
        "N  NN",
        "N   N",
    ],
    'O': [
        " OOO ",
        "O   O",
        "O   O",
        "O   O",
        " OOO ",
    ],
    'P': [
        "PPP  ",
        "P   P",
        "PPP  ",
        "P    ",
        "P    ",
    ],
    'Q': [
        " QQQ ",
        "Q   Q",
        "Q   Q",
        "Q Q Q",
        " QQ Q",
    ],
    'R': [
        "RRR  ",
        "R   R",
        "RRR  ",
        "R R  ",
        "R  R ",
    ],
    'S': [
        " SSS ",
        "S    ",
        " SSS ",
        "    S",
        " SSS ",
    ],
    'T': [
        "TTTTT",
        "  T  ",
        "  T  ",
        "  T  ",
        "  T  ",
    ],
    'U': [
        "U   U",
        "U   U",
        "U   U",
        "U   U",
        " UUU ",
    ],
    'V': [
        "V   V",
        "V   V",
        "V   V",
        " V V ",
        "  V  ",
    ],
    'W': [
        "W   W",
        "W   W",
        "W W W",
        "W W W",
        "W   W",
    ],
    'X': [
        "X   X",
        "X   X",
        " X X ",
        "X   X",
        "X   X",
    ],
    'Y': [
        "Y   Y",
        "Y   Y",
        " Y Y ",
        "  Y  ",
        "  Y  ",
    ],
    'Z': [
        "ZZZZZ",
        "   Z ",
        "  Z  ",
        " Z   ",
        "ZZZZZ",
    ],
    # Додайте ASCII-арт для інших символів тут
}